
services:
  backend:
    build:
      context: ./src/server
      dockerfile: Dockerfile
    image: eventhub:backend
    env_file:
      - ./.env                       
    ports:
      - "3000:3000"
    volumes:
      - ./src/server:/app
      - /app/node_modules
    networks:
      - eventhub-net

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    image: eventhub:frontend
    command: ["npm", "run", "dev"]
    env_file:
      - ./.env                       
    ports:
      - "5173:5173"
    volumes:
      - ./:/app                       
      - /app/node_modules
    depends_on:
      - backend                       
    networks:
      - eventhub-net

networks:
  eventhub-net:
    driver: bridge                    
