import { Code, Book, Wrench, FlaskConical, Radio, Building } from "lucide-react"

// Theme colors
export const colors = {
  primary: "#2c7873", // Teal for primary actions
  primaryLight: "#d5efe6", // Light mint green for backgrounds
  secondary: "#fde8e6", // Soft pink for secondary elements
  textPrimary: "#000000", // Black for primary text
}

// Sample department data with icons and event status
export const departments = [
  {
    name: "Computer Science",
    icon: Code,
    events: [
      {
        id: "cs1",
        title: "Tech Hackathon 2025",
        type: "Technical",
        date: "April 15, 2025",
        time: "9:00 AM - 6:00 PM",
        location: "Main Auditorium",
        registrations: 78,
        image: "/api/placeholder/320/180",
        status: "upcoming",
      },
      {
        id: "cs2",
        title: "AI Workshop",
        type: "Workshop",
        date: "April 25, 2025",
        time: "2:00 PM - 5:00 PM",
        location: "Lab 101",
        registrations: 42,
        image: "https://qcqrjeqovkxebviqxzlc.supabase.co/storage/v1/object/public/event-images/events/hackathon-flyer-design-template-4fc2cfe7a4d4b3913e5192047a0bb29d_screen.jpg ",
        status: "upcoming",
      },
      {
        id: "cs3",
        title: "Web Development Bootcamp",
        type: "Workshop",
        date: "May 10, 2025",
        time: "10:00 AM - 4:00 PM",
        location: "Lab 102",
        registrations: 35,
        image: "/api/placeholder/320/180",
        status: "upcoming",
      },
      {
        id: "cs4",
        title: "Coding Competition",
        type: "Competition",
        date: "May 20, 2025",
        time: "1:00 PM - 7:00 PM",
        location: "Computer Lab 201",
        registrations: 64,
        image: "/api/placeholder/320/180",
        status: "upcoming",
      },
      {
        id: "cs5",
        title: "Python Bootcamp",
        type: "Workshop",
        date: "April 11-12, 2025",
        time: "9:00 AM - 5:00 PM",
        location: "Lab 103",
        registrations: 45,
        image: "https://qcqrjeqovkxebviqxzlc.supabase.co/storage/v1/object/public/event-images/events/hackathon-flyer-design-template-4fc2cfe7a4d4b3913e5192047a0bb29d_screen.jpg ",
        status: "ongoing",
      },
      {
        id: "cs6",
        title: "Introduction to Cybersecurity",
        type: "Seminar",
        date: "March 15, 2025",
        time: "2:00 PM - 5:00 PM",
        location: "Lecture Hall A",
        registrations: 60,
        image: "/api/placeholder/320/180",
        status: "completed",
      },
    ],
  },
  {
    name: "Mechanical Engineering",
    icon: Wrench,
    events: [
      {
        id: "me1",
        title: "CAD/CAM Workshop",
        type: "Workshop",
        date: "April 18, 2025",
        time: "10:00 AM - 4:00 PM",
        location: "Design Studio",
        registrations: 45,
        image: "/api/placeholder/320/180",
        status: "upcoming",
      },
      {
        id: "me2",
        title: "Robotics Competition",
        type: "Competition",
        date: "May 5, 2025",
        time: "9:00 AM - 6:00 PM",
        location: "Robotics Lab",
        registrations: 32,
        image: "/api/placeholder/320/180",
        status: "upcoming",
      },
      {
        id: "me3",
        title: "Industry Talk: Future of Manufacturing",
        type: "Seminar",
        date: "May 12, 2025",
        time: "3:00 PM - 5:00 PM",
        location: "Lecture Hall B",
        registrations: 56,
        image: "/api/placeholder/320/180",
        status: "upcoming",
      },
      {
        id: "me4",
        title: "Machine Design Challenge",
        type: "Competition",
        date: "May 25, 2025",
        time: "10:00 AM - 5:00 PM",
        location: "Engineering Workshop",
        registrations: 28,
        image: "/api/placeholder/320/180",
        status: "upcoming",
      },
      {
        id: "me5",
        title: "3D Printing Workshop",
        type: "Workshop",
        date: "April 10-13, 2025",
        time: "1:00 PM - 5:00 PM",
        location: "Fabrication Lab",
        registrations: 24,
        image: "/api/placeholder/320/180",
        status: "ongoing",
      },
      {
        id: "me6",
        title: "Automotive Engineering Basics",
        type: "Course",
        date: "March 20, 2025",
        time: "9:00 AM - 3:00 PM",
        location: "Auto Workshop",
        registrations: 40,
        image: "/api/placeholder/320/180",
        status: "completed",
      },
    ],
  },
  {
    name: "Electronics & Telecommunication",
    icon: Radio,
    events: [
      {
        id: "entc1",
        title: "IoT Development Workshop",
        type: "Workshop",
        date: "April 17, 2025",
        time: "10:00 AM - 5:00 PM",
        location: "Electronics Lab",
        registrations: 62,
        image: "/api/placeholder/320/180",
        status: "upcoming",
      },
      {
        id: "entc2",
        title: "Embedded Systems Symposium",
        type: "Symposium",
        date: "April 28, 2025",
        time: "9:00 AM - 6:00 PM",
        location: "Main Auditorium",
        registrations: 85,
        image: "/api/placeholder/320/180",
        status: "upcoming",
      },
      {
        id: "entc3",
        title: "PCB Design Contest",
        type: "Competition",
        date: "May 7, 2025",
        time: "1:00 PM - 7:00 PM",
        location: "Digital Lab",
        registrations: 40,
        image: "/api/placeholder/320/180",
        status: "upcoming",
      },
      {
        id: "entc4",
        title: "5G Technology Seminar",
        type: "Seminar",
        date: "May 20, 2025",
        time: "2:00 PM - 5:00 PM",
        location: "Lecture Hall C",
        registrations: 92,
        image: "/api/placeholder/320/180",
        status: "upcoming",
      },
      {
        id: "entc5",
        title: "Arduino Challenge",
        type: "Workshop",
        date: "April 9-12, 2025",
        time: "10:00 AM - 4:00 PM",
        location: "ENTC Workshop",
        registrations: 38,
        image: "/api/placeholder/320/180",
        status: "ongoing",
      },
      {
        id: "entc6",
        title: "Antenna Design Workshop",
        type: "Workshop",
        date: "March 22, 2025",
        time: "9:00 AM - 4:00 PM",
        location: "RF Lab",
        registrations: 45,
        image: "/api/placeholder/320/180",
        status: "completed",
      },
    ],
  },
  {
    name: "Civil Engineering",
    icon: Building,
    events: [
      {
        id: "ce1",
        title: "Sustainable Infrastructure Conference",
        type: "Conference",
        date: "April 22, 2025",
        time: "9:00 AM - 5:00 PM",
        location: "Civil Engineering Block",
        registrations: 75,
        image: "/api/placeholder/320/180",
        status: "upcoming",
      },
      {
        id: "ce2",
        title: "Bridge Design Competition",
        type: "Competition",
        date: "May 5, 2025",
        time: "10:00 AM - 6:00 PM",
        location: "Structures Lab",
        registrations: 48,
        image: "/api/placeholder/320/180",
        status: "upcoming",
      },
      {
        id: "ce3",
        title: "GIS and Remote Sensing Workshop",
        type: "Workshop",
        date: "May 15, 2025",
        time: "1:00 PM - 5:00 PM",
        location: "Survey Lab",
        registrations: 36,
        image: "/api/placeholder/320/180",
        status: "upcoming",
      },
      {
        id: "ce4",
        title: "Green Building Certification Seminar",
        type: "Seminar",
        date: "May 25, 2025",
        time: "2:00 PM - 4:00 PM",
        location: "Lecture Hall D",
        registrations: 65,
        image: "/api/placeholder/320/180",
        status: "upcoming",
      },
      {
        id: "ce5",
        title: "Urban Planning Workshop",
        type: "Workshop",
        date: "April 10-13, 2025",
        time: "10:00 AM - 3:00 PM",
        location: "Planning Studio",
        registrations: 32,
        image: "/api/placeholder/320/180",
        status: "ongoing",
      },
      {
        id: "ce6",
        title: "Transportation Engineering Symposium",
        type: "Symposium",
        date: "March 25, 2025",
        time: "9:00 AM - 4:00 PM",
        location: "Civil Seminar Hall",
        registrations: 60,
        image: "/api/placeholder/320/180",
        status: "completed",
      },
    ],
  }
];